---
- name: Aktualizacja repozytori贸w APT i pakiet贸w NETCLOUD24.COM
  hosts: DEV
  become: true

  tasks:
    - name: Aktualizacja repozytori贸w APT
      apt:
        update_cache: yes

    - name: Aktualizacja pakiet贸w
      apt:
        upgrade: yes
